camera0: 0
camera1: 2
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 2.1
checkerboard_rows: 7
checkerboard_columns: 9
cooldown: 100
